import type { Recipe } from "./types"

export const mockRecipes: Recipe[] = [
  // Italian Cuisine
  {
    id: "italian-1",
    title: "Classic Margherita Pizza",
    cuisine: "Italian",
    cookingTime: "30 mins",
    ingredients: [
      "Pizza dough",
      "2 tomatoes, sliced",
      "Fresh mozzarella cheese",
      "Fresh basil leaves",
      "2 tbsp olive oil",
      "1 clove garlic, minced",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 475°F (245°C).",
      "Roll out pizza dough on a floured surface.",
      "Brush the dough with olive oil and minced garlic.",
      "Arrange tomato slices and torn mozzarella on top.",
      "Season with salt and pepper.",
      "Bake for 10-12 minutes until crust is golden.",
      "Top with fresh basil leaves before serving.",
    ],
    tags: ["Vegetarian", "Quick", "Pizza"],
    nutrition: [
      { name: "Calories", value: "320 kcal" },
      { name: "Protein", value: "12g" },
      { name: "Carbs", value: "42g" },
      { name: "Fat", value: "14g" },
    ],
  },
  {
    id: "italian-2",
    title: "Creamy Mushroom Risotto",
    cuisine: "Italian",
    cookingTime: "40 mins",
    ingredients: [
      "1 cup Arborio rice",
      "8 oz mushrooms, sliced",
      "1 onion, finely diced",
      "2 cloves garlic, minced",
      "4 cups vegetable broth, warm",
      "1/2 cup white wine",
      "1/2 cup Parmesan cheese, grated",
      "2 tbsp butter",
      "2 tbsp olive oil",
      "Fresh thyme leaves",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Heat olive oil in a large pan over medium heat.",
      "Add onions and cook until translucent, about 3 minutes.",
      "Add mushrooms and garlic, cook until mushrooms are soft.",
      "Add Arborio rice and stir for 1-2 minutes until translucent at the edges.",
      "Pour in white wine and stir until absorbed.",
      "Add warm broth one ladle at a time, stirring constantly until absorbed before adding more.",
      "Continue until rice is creamy and al dente, about 20-25 minutes.",
      "Stir in butter and Parmesan cheese.",
      "Season with salt, pepper, and fresh thyme leaves.",
    ],
    tags: ["Vegetarian", "Comfort Food"],
    nutrition: [
      { name: "Calories", value: "420 kcal" },
      { name: "Protein", value: "10g" },
      { name: "Carbs", value: "58g" },
      { name: "Fat", value: "16g" },
    ],
  },
  {
    id: "italian-3",
    title: "Tiramisu",
    cuisine: "Italian",
    cookingTime: "4 hours (including chilling)",
    ingredients: [
      "6 egg yolks",
      "3/4 cup white sugar",
      "2/3 cup milk",
      "1 1/4 cups heavy cream",
      "1/2 tsp vanilla extract",
      "1 lb mascarpone cheese",
      "1 cup strong brewed coffee, cooled",
      "2 tbsp rum (optional)",
      "24 ladyfinger cookies",
      "1 tbsp cocoa powder",
    ],
    instructions: [
      "In a medium saucepan, whisk together egg yolks and sugar until well blended.",
      "Whisk in milk and cook over medium heat, stirring constantly, until mixture boils.",
      "Boil gently for 1 minute, then remove from heat and allow to cool slightly.",
      "Cover tightly and chill in refrigerator for 1 hour.",
      "In a medium bowl, beat cream with vanilla until stiff peaks form.",
      "Whisk mascarpone into yolk mixture until smooth.",
      "Combine coffee and rum in a small bowl.",
      "Dip ladyfingers into coffee mixture and arrange in the bottom of a 7x11 inch dish.",
      "Spread half of mascarpone mixture over ladyfingers, then half of whipped cream.",
      "Repeat layers and sprinkle with cocoa powder.",
      "Cover and refrigerate for at least 2-3 hours before serving.",
    ],
    tags: ["Dessert", "No-Bake"],
    nutrition: [
      { name: "Calories", value: "380 kcal" },
      { name: "Protein", value: "6g" },
      { name: "Carbs", value: "32g" },
      { name: "Fat", value: "26g" },
    ],
  },

  // Indian Cuisine
  {
    id: "indian-1",
    title: "Butter Chicken (Murgh Makhani)",
    cuisine: "Indian",
    cookingTime: "45 mins",
    ingredients: [
      "1.5 lbs chicken breast, cut into pieces",
      "1 cup plain yogurt",
      "2 tbsp lemon juice",
      "2 tsp ground cumin",
      "2 tsp ground red chili powder",
      "2 tsp ground coriander",
      "1 tbsp ginger paste",
      "1 tbsp garlic paste",
      "1 cup tomato puree",
      "1 cup heavy cream",
      "2 tbsp butter",
      "1 tsp garam masala",
      "Fresh cilantro for garnish",
      "Salt to taste",
    ],
    instructions: [
      "Marinate chicken with yogurt, lemon juice, cumin, red chili powder, and salt for at least 1 hour.",
      "Heat butter in a large skillet over medium heat.",
      "Add ginger and garlic paste, cook for 1 minute until fragrant.",
      "Add marinated chicken and cook until no longer pink, about 10 minutes.",
      "Stir in tomato puree, cover, and simmer for 10 minutes.",
      "Add cream and garam masala, simmer for another 5 minutes.",
      "Garnish with fresh cilantro and serve with naan or rice.",
    ],
    tags: ["Spicy", "Protein-Rich"],
    nutrition: [
      { name: "Calories", value: "480 kcal" },
      { name: "Protein", value: "32g" },
      { name: "Carbs", value: "12g" },
      { name: "Fat", value: "34g" },
    ],
  },
  {
    id: "indian-2",
    title: "Vegetable Biryani",
    cuisine: "Indian",
    cookingTime: "50 mins",
    ingredients: [
      "2 cups basmati rice",
      "4 cups water",
      "1 large onion, thinly sliced",
      "2 carrots, diced",
      "1 cup green peas",
      "1 bell pepper, diced",
      "2 potatoes, cubed",
      "2 tomatoes, chopped",
      "1/4 cup yogurt",
      "2 tbsp biryani masala",
      "1 tsp turmeric powder",
      "1 tsp cumin seeds",
      "4 cloves",
      "2 bay leaves",
      "1 cinnamon stick",
      "2 green cardamom pods",
      "3 tbsp ghee or oil",
      "Fresh mint and cilantro for garnish",
      "Salt to taste",
    ],
    instructions: [
      "Wash rice and soak for 30 minutes, then drain.",
      "Heat ghee in a large pot, add cumin seeds, cloves, bay leaves, cinnamon, and cardamom.",
      "Add sliced onions and cook until golden brown.",
      "Add vegetables and cook for 5 minutes.",
      "Add biryani masala, turmeric, and salt. Mix well.",
      "Add yogurt and tomatoes, cook for 3 minutes.",
      "Add rice and water. Bring to a boil, then reduce heat to low.",
      "Cover and cook for 15-20 minutes until rice is done.",
      "Garnish with fresh mint and cilantro before serving.",
    ],
    tags: ["Vegetarian", "One-Pot"],
    nutrition: [
      { name: "Calories", value: "380 kcal" },
      { name: "Protein", value: "8g" },
      { name: "Carbs", value: "62g" },
      { name: "Fat", value: "12g" },
    ],
  },
  {
    id: "indian-3",
    title: "Masala Chai",
    cuisine: "Indian",
    cookingTime: "15 mins",
    ingredients: [
      "2 cups water",
      "2 cups milk",
      "4 tsp black tea leaves (or 4 tea bags)",
      "1 inch ginger, crushed",
      "4 cardamom pods, crushed",
      "2 cinnamon sticks",
      "4 cloves",
      "1/4 tsp black peppercorns",
      "Sugar to taste",
    ],
    instructions: [
      "Bring water to a boil in a saucepan.",
      "Add crushed ginger, cardamom, cinnamon sticks, cloves, and peppercorns.",
      "Simmer for 5 minutes to infuse the spices.",
      "Add tea leaves and simmer for 2 more minutes.",
      "Add milk and bring to a boil.",
      "Reduce heat and simmer for 2 minutes.",
      "Add sugar to taste and stir until dissolved.",
      "Strain into cups and serve hot.",
    ],
    tags: ["Beverage", "Spiced"],
    nutrition: [
      { name: "Calories", value: "120 kcal" },
      { name: "Protein", value: "4g" },
      { name: "Carbs", value: "16g" },
      { name: "Fat", value: "4g" },
    ],
  },

  // Chinese Cuisine
  {
    id: "chinese-1",
    title: "Kung Pao Chicken",
    cuisine: "Chinese",
    cookingTime: "30 mins",
    ingredients: [
      "1 lb chicken breast, diced",
      "1/2 cup peanuts",
      "2 red bell peppers, diced",
      "2 green onions, sliced",
      "3 dried red chilies",
      "2 cloves garlic, minced",
      "1 inch ginger, minced",
      "2 tbsp soy sauce",
      "1 tbsp hoisin sauce",
      "1 tbsp rice vinegar",
      "1 tsp sesame oil",
      "1 tbsp cornstarch",
      "2 tbsp vegetable oil",
      "1 tsp Sichuan peppercorns (optional)",
      "Salt to taste",
    ],
    instructions: [
      "Mix chicken with 1 tbsp soy sauce, 1 tsp sesame oil, and cornstarch. Let marinate for 15 minutes.",
      "Heat vegetable oil in a wok over high heat.",
      "Add dried chilies and Sichuan peppercorns, stir-fry for 30 seconds.",
      "Add garlic and ginger, stir-fry for another 30 seconds.",
      "Add chicken and stir-fry until no longer pink, about 5 minutes.",
      "Add bell peppers and cook for 2 minutes.",
      "Mix remaining soy sauce, hoisin sauce, and rice vinegar in a small bowl.",
      "Pour sauce into the wok and stir to coat.",
      "Add peanuts and green onions, stir-fry for 1 minute.",
      "Serve hot with steamed rice.",
    ],
    tags: ["Spicy", "Stir-Fry"],
    nutrition: [
      { name: "Calories", value: "420 kcal" },
      { name: "Protein", value: "35g" },
      { name: "Carbs", value: "18g" },
      { name: "Fat", value: "24g" },
    ],
  },
  {
    id: "chinese-2",
    title: "Hot and Sour Soup",
    cuisine: "Chinese",
    cookingTime: "25 mins",
    ingredients: [
      "6 cups chicken broth",
      "8 oz firm tofu, sliced into strips",
      "1 cup shiitake mushrooms, sliced",
      "1/4 cup bamboo shoots, julienned",
      "2 eggs, beaten",
      "3 tbsp rice vinegar",
      "2 tbsp soy sauce",
      "1 tsp white pepper",
      "1 tbsp chili oil",
      "2 tbsp cornstarch mixed with 3 tbsp water",
      "2 green onions, sliced",
      "1 tsp sesame oil",
      "Salt to taste",
    ],
    instructions: [
      "Bring chicken broth to a boil in a large pot.",
      "Add mushrooms and bamboo shoots, simmer for 5 minutes.",
      "Add tofu, soy sauce, rice vinegar, and white pepper.",
      "Stir in cornstarch mixture to thicken the soup.",
      "Slowly pour beaten eggs into the soup while stirring gently.",
      "Add chili oil and sesame oil.",
      "Garnish with green onions before serving.",
    ],
    tags: ["Soup", "Spicy"],
    nutrition: [
      { name: "Calories", value: "180 kcal" },
      { name: "Protein", value: "14g" },
      { name: "Carbs", value: "12g" },
      { name: "Fat", value: "10g" },
    ],
  },
  {
    id: "chinese-3",
    title: "Vegetable Spring Rolls",
    cuisine: "Chinese",
    cookingTime: "40 mins",
    ingredients: [
      "12 spring roll wrappers",
      "2 cups cabbage, shredded",
      "1 carrot, julienned",
      "1 cup bean sprouts",
      "4 shiitake mushrooms, thinly sliced",
      "2 green onions, chopped",
      "2 cloves garlic, minced",
      "1 tbsp ginger, minced",
      "2 tbsp soy sauce",
      "1 tsp sesame oil",
      "1 tbsp vegetable oil, plus more for frying",
      "Sweet chili sauce for dipping",
    ],
    instructions: [
      "Heat 1 tbsp vegetable oil in a wok over high heat.",
      "Add garlic and ginger, stir-fry for 30 seconds.",
      "Add cabbage, carrots, and mushrooms, stir-fry for 3 minutes.",
      "Add bean sprouts and green onions, cook for 1 minute.",
      "Stir in soy sauce and sesame oil, then remove from heat and let cool.",
      "Place a spring roll wrapper on a clean surface with a corner pointing toward you.",
      "Spoon 2 tbsp of filling near the corner closest to you.",
      "Fold the corner over the filling, then fold in the sides and roll tightly.",
      "Seal the edge with a little water.",
      "Heat oil for frying to 350°F (175°C).",
      "Fry spring rolls until golden brown, about 2-3 minutes.",
      "Drain on paper towels and serve with sweet chili sauce.",
    ],
    tags: ["Appetizer", "Vegetarian"],
    nutrition: [
      { name: "Calories", value: "220 kcal" },
      { name: "Protein", value: "5g" },
      { name: "Carbs", value: "28g" },
      { name: "Fat", value: "12g" },
    ],
  },

  // Mexican Cuisine
  {
    id: "mexican-1",
    title: "Chicken Enchiladas",
    cuisine: "Mexican",
    cookingTime: "45 mins",
    ingredients: [
      "2 cups cooked chicken, shredded",
      "8 flour tortillas",
      "2 cups enchilada sauce",
      "1 1/2 cups Mexican blend cheese, shredded",
      "1 onion, diced",
      "1 bell pepper, diced",
      "2 cloves garlic, minced",
      "1 tbsp olive oil",
      "1 tsp cumin",
      "1 tsp chili powder",
      "1/2 tsp oregano",
      "Sour cream for serving",
      "Fresh cilantro for garnish",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C).",
      "Heat olive oil in a skillet over medium heat.",
      "Add onion and bell pepper, cook until softened.",
      "Add garlic, cumin, chili powder, and oregano, cook for 1 minute.",
      "Stir in shredded chicken and 1/4 cup of enchilada sauce.",
      "Warm tortillas to make them pliable.",
      "Fill each tortilla with chicken mixture and roll up.",
      "Place enchiladas seam-side down in a baking dish.",
      "Pour remaining enchilada sauce over the top and sprinkle with cheese.",
      "Bake for 20-25 minutes until cheese is melted and bubbly.",
      "Garnish with cilantro and serve with sour cream.",
    ],
    tags: ["Dinner", "Spicy"],
    nutrition: [
      { name: "Calories", value: "420 kcal" },
      { name: "Protein", value: "28g" },
      { name: "Carbs", value: "38g" },
      { name: "Fat", value: "18g" },
    ],
  },
  {
    id: "mexican-2",
    title: "Guacamole",
    cuisine: "Mexican",
    cookingTime: "15 mins",
    ingredients: [
      "3 ripe avocados",
      "1 lime, juiced",
      "1/2 red onion, finely diced",
      "1 tomato, diced",
      "2 tbsp fresh cilantro, chopped",
      "1 jalapeño, seeds removed and minced",
      "1 clove garlic, minced",
      "1/2 tsp cumin",
      "Salt and pepper to taste",
      "Tortilla chips for serving",
    ],
    instructions: [
      "Cut avocados in half, remove pits, and scoop flesh into a bowl.",
      "Mash avocados with a fork, leaving some chunks for texture.",
      "Add lime juice and mix well to prevent browning.",
      "Fold in red onion, tomato, cilantro, jalapeño, and garlic.",
      "Season with cumin, salt, and pepper.",
      "Taste and adjust seasoning if needed.",
      "Serve immediately with tortilla chips or refrigerate with plastic wrap pressed directly onto the surface to prevent browning.",
    ],
    tags: ["Appetizer", "Vegetarian"],
    nutrition: [
      { name: "Calories", value: "180 kcal" },
      { name: "Protein", value: "2g" },
      { name: "Carbs", value: "12g" },
      { name: "Fat", value: "16g" },
    ],
  },
  {
    id: "mexican-3",
    title: "Churros with Chocolate Sauce",
    cuisine: "Mexican",
    cookingTime: "30 mins",
    ingredients: [
      "1 cup water",
      "1/2 cup butter",
      "1/4 tsp salt",
      "1 cup all-purpose flour",
      "3 eggs",
      "1/2 cup sugar",
      "1 tsp ground cinnamon",
      "Vegetable oil for frying",
      "For chocolate sauce:",
      "1 cup semi-sweet chocolate chips",
      "1/2 cup heavy cream",
      "1 tsp vanilla extract",
    ],
    instructions: [
      "In a saucepan, combine water, butter, and salt. Bring to a boil.",
      "Remove from heat and add flour all at once, stirring vigorously.",
      "Return to low heat and stir until mixture forms a ball, about 1 minute.",
      "Remove from heat and let cool for 5 minutes.",
      "Beat in eggs one at a time, mixing well after each addition.",
      "Transfer dough to a piping bag fitted with a star tip.",
      "Heat oil to 375°F (190°C) in a deep fryer or large pot.",
      "Pipe 4-inch strips of dough into the hot oil, cutting with scissors.",
      "Fry until golden brown, about 2 minutes per side.",
      "Drain on paper towels.",
      "Mix sugar and cinnamon, then roll churros in the mixture.",
      "For the sauce, heat heavy cream until just simmering.",
      "Pour over chocolate chips and let sit for 1 minute, then stir until smooth.",
      "Add vanilla extract and serve warm with churros.",
    ],
    tags: ["Dessert", "Sweet"],
    nutrition: [
      { name: "Calories", value: "320 kcal" },
      { name: "Protein", value: "4g" },
      { name: "Carbs", value: "36g" },
      { name: "Fat", value: "18g" },
    ],
  },

  // Thai Cuisine
  {
    id: "thai-1",
    title: "Pad Thai",
    cuisine: "Thai",
    cookingTime: "30 mins",
    ingredients: [
      "8 oz rice noodles",
      "2 tbsp vegetable oil",
      "2 eggs, beaten",
      "1 lb shrimp, peeled and deveined (or tofu for vegetarian)",
      "2 cloves garlic, minced",
      "1 shallot, minced",
      "1 cup bean sprouts",
      "2 green onions, chopped",
      "1/4 cup roasted peanuts, chopped",
      "Fresh cilantro for garnish",
      "Lime wedges for serving",
      "For sauce:",
      "3 tbsp fish sauce",
      "3 tbsp brown sugar",
      "2 tbsp tamarind paste",
      "1 tbsp rice vinegar",
      "1 tsp sriracha sauce",
    ],
    instructions: [
      "Soak rice noodles in hot water for 10 minutes until softened, then drain.",
      "Mix all sauce ingredients in a small bowl and set aside.",
      "Heat oil in a large wok or skillet over high heat.",
      "Add garlic and shallot, stir-fry for 30 seconds.",
      "Add shrimp (or tofu) and cook until pink, about 2-3 minutes.",
      "Push to one side of the pan and pour in beaten eggs.",
      "Scramble eggs until set, then mix with shrimp.",
      "Add drained noodles and sauce, toss to coat evenly.",
      "Stir-fry for 2-3 minutes until noodles are tender and sauce is absorbed.",
      "Add bean sprouts and green onions, toss for another minute.",
      "Serve topped with chopped peanuts, cilantro, and lime wedges.",
    ],
    tags: ["Stir-Fry", "Spicy"],
    nutrition: [
      { name: "Calories", value: "420 kcal" },
      { name: "Protein", value: "24g" },
      { name: "Carbs", value: "52g" },
      { name: "Fat", value: "14g" },
    ],
  },
  {
    id: "thai-2",
    title: "Tom Yum Soup",
    cuisine: "Thai",
    cookingTime: "25 mins",
    ingredients: [
      "6 cups chicken broth",
      "1 stalk lemongrass, bruised and cut into 2-inch pieces",
      "3 kaffir lime leaves",
      "1 inch galangal or ginger, sliced",
      "2 Thai chilies, sliced",
      "8 oz mushrooms, sliced",
      "1 lb shrimp, peeled and deveined",
      "2 tbsp fish sauce",
      "3 tbsp lime juice",
      "1 tsp sugar",
      "2 tbsp Thai chili paste (Nam Prik Pao)",
      "Fresh cilantro for garnish",
      "Green onions, sliced, for garnish",
    ],
    instructions: [
      "Bring chicken broth to a boil in a large pot.",
      "Add lemongrass, lime leaves, galangal, and Thai chilies.",
      "Reduce heat and simmer for 10 minutes to infuse flavors.",
      "Add mushrooms and simmer for 5 minutes.",
      "Add shrimp and cook until pink, about 2-3 minutes.",
      "Stir in fish sauce, lime juice, sugar, and chili paste.",
      "Taste and adjust seasoning if needed.",
      "Garnish with cilantro and green onions before serving.",
    ],
    tags: ["Soup", "Spicy"],
    nutrition: [
      { name: "Calories", value: "220 kcal" },
      { name: "Protein", value: "26g" },
      { name: "Carbs", value: "12g" },
      { name: "Fat", value: "8g" },
    ],
  },
  {
    id: "thai-3",
    title: "Mango Sticky Rice",
    cuisine: "Thai",
    cookingTime: "40 mins",
    ingredients: [
      "1 cup glutinous rice (sweet rice)",
      "1 1/2 cups water",
      "1 can (14 oz) coconut milk",
      "1/4 cup sugar",
      "1/2 tsp salt",
      "2 ripe mangoes, peeled and sliced",
      "1 tbsp toasted sesame seeds or mung beans for garnish",
    ],
    instructions: [
      "Rinse glutinous rice several times until water runs clear.",
      "Soak rice in water for at least 30 minutes, then drain.",
      "Steam rice for 25 minutes until tender.",
      "In a saucepan, heat 1 cup coconut milk, sugar, and salt until sugar dissolves.",
      "Pour 3/4 of the coconut mixture over the hot rice, stir gently, and let sit for 15 minutes to absorb.",
      "For the sauce, simmer remaining coconut milk until slightly thickened.",
      "Serve rice with mango slices, drizzle with coconut sauce, and sprinkle with sesame seeds.",
    ],
    tags: ["Dessert", "Sweet"],
    nutrition: [
      { name: "Calories", value: "380 kcal" },
      { name: "Protein", value: "5g" },
      { name: "Carbs", value: "62g" },
      { name: "Fat", value: "14g" },
    ],
  },

  // Japanese Cuisine
  {
    id: "japanese-1",
    title: "Chicken Teriyaki",
    cuisine: "Japanese",
    cookingTime: "25 mins",
    ingredients: [
      "1.5 lbs chicken thighs, boneless and skinless",
      "1/4 cup soy sauce",
      "1/4 cup mirin",
      "2 tbsp sake (or dry white wine)",
      "2 tbsp brown sugar",
      "1 tbsp honey",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "1 tbsp vegetable oil",
      "2 green onions, sliced",
      "1 tsp sesame seeds",
      "Steamed rice for serving",
    ],
    instructions: [
      "In a bowl, mix soy sauce, mirin, sake, brown sugar, honey, garlic, and ginger.",
      "Reserve 1/4 cup of the sauce for later.",
      "Marinate chicken in the remaining sauce for at least 30 minutes.",
      "Heat oil in a large skillet over medium-high heat.",
      "Remove chicken from marinade and pat dry.",
      "Cook chicken for 5-6 minutes per side until browned and cooked through.",
      "Pour reserved sauce over chicken and simmer until sauce thickens, about 2-3 minutes.",
      "Slice chicken and serve over steamed rice.",
      "Garnish with green onions and sesame seeds.",
    ],
    tags: ["Dinner", "Sweet & Savory"],
    nutrition: [
      { name: "Calories", value: "380 kcal" },
      { name: "Protein", value: "32g" },
      { name: "Carbs", value: "18g" },
      { name: "Fat", value: "20g" },
    ],
  },
  {
    id: "japanese-2",
    title: "Miso Soup",
    cuisine: "Japanese",
    cookingTime: "15 mins",
    ingredients: [
      "4 cups dashi stock (or vegetable broth)",
      "3 tbsp miso paste",
      "8 oz soft tofu, cubed",
      "2 green onions, sliced",
      "1/4 cup wakame seaweed, rehydrated",
      "1 sheet nori, cut into small pieces (optional)",
    ],
    instructions: [
      "Bring dashi stock to a simmer (do not boil).",
      "Place miso paste in a small bowl and add a ladleful of hot dashi.",
      "Whisk until smooth, then pour back into the pot.",
      "Add tofu and wakame, simmer for 2 minutes.",
      "Remove from heat and add green onions.",
      "Serve immediately, garnished with nori if desired.",
    ],
    tags: ["Soup", "Vegetarian"],
    nutrition: [
      { name: "Calories", value: "120 kcal" },
      { name: "Protein", value: "8g" },
      { name: "Carbs", value: "10g" },
      { name: "Fat", value: "6g" },
    ],
  },
  {
    id: "japanese-3",
    title: "Matcha Green Tea Ice Cream",
    cuisine: "Japanese",
    cookingTime: "4 hours (including freezing)",
    ingredients: [
      "2 cups heavy cream",
      "1 cup whole milk",
      "3/4 cup sugar",
      "Pinch of salt",
      "4 egg yolks",
      "2 tbsp matcha green tea powder",
      "1 tsp vanilla extract",
    ],
    instructions: [
      "In a saucepan, heat cream, milk, half the sugar, and salt until steaming.",
      "In a bowl, whisk egg yolks with remaining sugar until pale.",
      "Sift matcha powder into the egg mixture and whisk until smooth.",
      "Slowly pour hot cream mixture into egg mixture, whisking constantly.",
      "Return mixture to saucepan and cook over low heat, stirring constantly, until thickened.",
      "Strain custard through a fine-mesh sieve into a bowl.",
      "Stir in vanilla extract and let cool completely.",
      "Refrigerate for at least 2 hours or overnight.",
      "Churn in an ice cream maker according to manufacturer's instructions.",
      "Transfer to a container and freeze until firm, about 2 hours.",
    ],
    tags: ["Dessert", "Frozen"],
    nutrition: [
      { name: "Calories", value: "320 kcal" },
      { name: "Protein", value: "4g" },
      { name: "Carbs", value: "26g" },
      { name: "Fat", value: "24g" },
    ],
  },

  // Mediterranean Cuisine
  {
    id: "mediterranean-1",
    title: "Greek Salad",
    cuisine: "Mediterranean",
    cookingTime: "15 mins",
    ingredients: [
      "1 large cucumber, diced",
      "4 tomatoes, diced",
      "1 red onion, thinly sliced",
      "1 bell pepper, diced",
      "1 cup Kalamata olives",
      "8 oz feta cheese, cubed",
      "2 tbsp fresh oregano, chopped",
      "1/4 cup extra virgin olive oil",
      "2 tbsp red wine vinegar",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large bowl, combine cucumber, tomatoes, red onion, bell pepper, and olives.",
      "In a small bowl, whisk together olive oil, red wine vinegar, dried oregano, salt, and pepper.",
      "Pour dressing over the vegetables and toss gently.",
      "Add feta cheese and fresh oregano, toss lightly.",
      "Let sit for 10 minutes before serving to allow flavors to meld.",
    ],
    tags: ["Salad", "Vegetarian"],
    nutrition: [
      { name: "Calories", value: "280 kcal" },
      { name: "Protein", value: "8g" },
      { name: "Carbs", value: "12g" },
      { name: "Fat", value: "22g" },
    ],
  },
  {
    id: "mediterranean-2",
    title: "Hummus with Pita",
    cuisine: "Mediterranean",
    cookingTime: "10 mins",
    ingredients: [
      "1 can (15 oz) chickpeas, drained and rinsed",
      "1/4 cup tahini",
      "3 tbsp lemon juice",
      "2 cloves garlic, minced",
      "2 tbsp olive oil, plus more for drizzling",
      "1/2 tsp ground cumin",
      "2-3 tbsp water",
      "Salt to taste",
      "Paprika for garnish",
      "Fresh parsley, chopped, for garnish",
      "Pita bread for serving",
    ],
    instructions: [
      "In a food processor, combine chickpeas, tahini, lemon juice, garlic, olive oil, and cumin.",
      "Process until smooth, adding water as needed to reach desired consistency.",
      "Season with salt to taste.",
      "Transfer to a serving bowl and create a well in the center.",
      "Drizzle with olive oil and sprinkle with paprika and parsley.",
      "Serve with warm pita bread.",
    ],
    tags: ["Appetizer", "Vegetarian"],
    nutrition: [
      { name: "Calories", value: "220 kcal" },
      { name: "Protein", value: "6g" },
      { name: "Carbs", value: "24g" },
      { name: "Fat", value: "12g" },
    ],
  },
  {
    id: "mediterranean-3",
    title: "Baklava",
    cuisine: "Mediterranean",
    cookingTime: "1 hour 30 mins",
    ingredients: [
      "1 package phyllo dough, thawed",
      "1 cup butter, melted",
      "2 cups walnuts, finely chopped",
      "1 cup pistachios, finely chopped",
      "1 tsp ground cinnamon",
      "1/4 tsp ground cloves",
      "1 cup sugar",
      "1 cup water",
      "1/2 cup honey",
      "1 tbsp lemon juice",
      "1 cinnamon stick",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C).",
      "Mix walnuts, pistachios, cinnamon, and cloves in a bowl.",
      "Brush a 9x13 inch baking dish with melted butter.",
      "Layer 8 sheets of phyllo dough, brushing each with butter.",
      "Sprinkle 1/3 of the nut mixture over the dough.",
      "Layer 4 more sheets of phyllo, brushing each with butter.",
      "Sprinkle another 1/3 of the nut mixture.",
      "Repeat with 4 more sheets and the remaining nut mixture.",
      "Top with 8 sheets of phyllo, brushing each with butter.",
      "Cut into diamond or square shapes.",
      "Bake for 50 minutes until golden and crisp.",
      "While baking, make the syrup: combine sugar, water, honey, lemon juice, and cinnamon stick in a saucepan.",
      "Bring to a boil, then simmer for 10 minutes.",
      "Remove cinnamon stick and let cool slightly.",
      "Pour cooled syrup over hot baklava.",
      "Let cool completely before serving.",
    ],
    tags: ["Dessert", "Sweet"],
    nutrition: [
      { name: "Calories", value: "380 kcal" },
      { name: "Protein", value: "6g" },
      { name: "Carbs", value: "42g" },
      { name: "Fat", value: "22g" },
    ],
  },

  // French Cuisine
  {
    id: "french-1",
    title: "Coq au Vin",
    cuisine: "French",
    cookingTime: "1 hour 30 mins",
    ingredients: [
      "8 chicken thighs",
      "8 oz bacon, diced",
      "2 cups red wine (preferably Burgundy)",
      "2 cups chicken broth",
      "1 onion, diced",
      "2 carrots, sliced",
      "8 oz mushrooms, quartered",
      "3 cloves garlic, minced",
      "2 tbsp tomato paste",
      "1 bouquet garni (thyme, parsley, bay leaf)",
      "2 tbsp butter",
      "2 tbsp flour",
      "Fresh parsley, chopped, for garnish",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Season chicken with salt and pepper.",
      "In a large Dutch oven, cook bacon until crisp. Remove and set aside.",
      "Brown chicken in bacon fat, then remove and set aside.",
      "Add onions, carrots, and garlic to the pot, cook until softened.",
      "Stir in tomato paste and flour, cook for 1 minute.",
      "Slowly add wine and broth, stirring to combine.",
      "Return chicken and bacon to the pot, add bouquet garni.",
      "Bring to a simmer, cover, and cook for 45 minutes.",
      "Add mushrooms and cook for another 15 minutes.",
      "Remove chicken and vegetables, strain sauce if desired.",
      "Return sauce to the pot and simmer until thickened.",
      "Return chicken and vegetables to the sauce, warm through.",
      "Garnish with fresh parsley before serving.",
    ],
    tags: ["Dinner", "Slow-Cooked"],
    nutrition: [
      { name: "Calories", value: "480 kcal" },
      { name: "Protein", value: "36g" },
      { name: "Carbs", value: "12g" },
      { name: "Fat", value: "28g" },
    ],
  },
  {
    id: "french-2",
    title: "Crème Brûlée",
    cuisine: "French",
    cookingTime: "3 hours (including chilling)",
    ingredients: [
      "2 cups heavy cream",
      "1 vanilla bean, split and scraped (or 1 tsp vanilla extract)",
      "5 egg yolks",
      "1/2 cup sugar, plus more for topping",
      "Pinch of salt",
    ],
    instructions: [
      "Preheat oven to 325°F (165°C).",
      "In a saucepan, heat cream and vanilla bean (if using) until steaming.",
      "In a bowl, whisk egg yolks, sugar, and salt until pale.",
      "Slowly pour hot cream into egg mixture, whisking constantly.",
      "If using vanilla extract, add it now.",
      "Strain custard through a fine-mesh sieve.",
      "Pour into ramekins and place in a baking dish.",
      "Fill baking dish with hot water halfway up the sides of the ramekins.",
      "Bake for 30-35 minutes until edges are set but center is still wobbly.",
      "Remove from water bath and cool completely.",
      "Refrigerate for at least 2 hours or overnight.",
      "Before serving, sprinkle a thin layer of sugar on top.",
      "Use a kitchen torch to caramelize the sugar until golden and crisp.",
      "Let sit for 1 minute before serving.",
    ],
    tags: ["Dessert", "Elegant"],
    nutrition: [
      { name: "Calories", value: "420 kcal" },
      { name: "Protein", value: "6g" },
      { name: "Carbs", value: "32g" },
      { name: "Fat", value: "32g" },
    ],
  },
  {
    id: "french-3",
    title: "French Onion Soup",
    cuisine: "French",
    cookingTime: "1 hour 15 mins",
    ingredients: [
      "4 large onions, thinly sliced",
      "3 tbsp butter",
      "1 tbsp olive oil",
      "1 tsp sugar",
      "2 cloves garlic, minced",
      "1/4 cup dry white wine",
      "6 cups beef broth",
      "1 bay leaf",
      "2 sprigs fresh thyme",
      "1 baguette, sliced",
      "2 cups Gruyère cheese, grated",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large pot, melt butter with olive oil over medium heat.",
      "Add onions and sugar, cook slowly until deeply caramelized, about 30-40 minutes, stirring occasionally.",
      "Add garlic and cook for 1 minute.",
      "Pour in wine and scrape up any browned bits from the bottom of the pot.",
      "Add beef broth, bay leaf, and thyme. Bring to a simmer.",
      "Cover and simmer for 30 minutes.",
      "Preheat broiler.",
      "Toast baguette slices until golden.",
      "Ladle soup into oven-safe bowls.",
      "Place a toasted baguette slice on top of each bowl of soup.",
      "Sprinkle generously with Gruyère cheese.",
      "Place under broiler until cheese is melted and bubbly, about 2-3 minutes.",
      "Serve immediately.",
    ],
    tags: ["Soup", "Comfort Food"],
    nutrition: [
      { name: "Calories", value: "380 kcal" },
      { name: "Protein", value: "18g" },
      { name: "Carbs", value: "32g" },
      { name: "Fat", value: "20g" },
    ],
  },

  // Korean Cuisine
  {
    id: "korean-1",
    title: "Bibimbap",
    cuisine: "Korean",
    cookingTime: "45 mins",
    ingredients: [
      "2 cups cooked white rice",
      "8 oz beef sirloin, thinly sliced",
      "1 cucumber, julienned",
      "1 carrot, julienned",
      "1 zucchini, julienned",
      "2 cups spinach",
      "2 eggs",
      "4 tbsp vegetable oil, divided",
      "2 tbsp sesame oil",
      "2 tbsp soy sauce",
      "1 tbsp sugar",
      "2 cloves garlic, minced",
      "2 tbsp gochujang (Korean chili paste)",
      "Sesame seeds for garnish",
    ],
    instructions: [
      "Marinate beef in 1 tbsp soy sauce, 1 tsp sugar, and 1 clove minced garlic for 30 minutes.",
      "Blanch spinach for 30 seconds, drain, and season with 1 tsp sesame oil and a pinch of salt.",
      "Sauté carrots in 1 tbsp vegetable oil for 2 minutes, season with salt.",
      "Sauté zucchini in 1 tbsp vegetable oil for 2 minutes, season with salt.",
      "Sauté cucumber in 1 tbsp vegetable oil for 1 minute, season with salt.",
      "Cook marinated beef in 1 tbsp vegetable oil until browned.",
      "Fry eggs sunny-side up.",
      "Mix gochujang with 1 tbsp sesame oil, 1 tbsp soy sauce, 1 tsp sugar, and 1 clove minced garlic.",
      "To serve, place rice in bowls and arrange vegetables and beef on top.",
      "Place fried egg on top and drizzle with gochujang sauce.",
      "Sprinkle with sesame seeds before serving.",
    ],
    tags: ["Bowl", "Spicy"],
    nutrition: [
      { name: "Calories", value: "480 kcal" },
      { name: "Protein", value: "26g" },
      { name: "Carbs", value: "42g" },
      { name: "Fat", value: "24g" },
    ],
  },
  {
    id: "korean-2",
    title: "Kimchi Jjigae (Kimchi Stew)",
    cuisine: "Korean",
    cookingTime: "35 mins",
    ingredients: [
      "2 cups kimchi, chopped",
      "1/2 cup kimchi juice",
      "8 oz pork belly, sliced",
      "1 block tofu, cubed",
      "1 onion, sliced",
      "2 green onions, chopped",
      "2 cloves garlic, minced",
      "1 tbsp gochugaru (Korean red pepper flakes)",
      "1 tbsp gochujang (Korean chili paste)",
      "1 tsp sugar",
      "4 cups water or broth",
      "1 tbsp vegetable oil",
    ],
    instructions: [
      "Heat oil in a pot over medium heat.",
      "Add pork belly and cook until fat renders, about 3-4 minutes.",
      "Add kimchi and stir-fry for 2 minutes.",
      "Add garlic, gochugaru, gochujang, and sugar. Stir to combine.",
      "Pour in water or broth and kimchi juice. Bring to a boil.",
      "Reduce heat and simmer for 20 minutes.",
      "Add tofu and simmer for another 5 minutes.",
      "Garnish with green onions before serving.",
    ],
    tags: ["Soup", "Spicy"],
    nutrition: [
      { name: "Calories", value: "380 kcal" },
      { name: "Protein", value: "22g" },
      { name: "Carbs", value: "18g" },
      { name: "Fat", value: "26g" },
    ],
  },
  {
    id: "korean-3",
    title: "Kimchi Fried Rice",
    cuisine: "Korean",
    cookingTime: "20 mins",
    ingredients: [
      "2 cups cooked rice, preferably day-old",
      "1 cup kimchi, chopped",
      "1/4 cup kimchi juice",
      "2 eggs",
      "2 green onions, chopped",
      "1 tbsp vegetable oil",
      "1 tbsp sesame oil",
      "1 tbsp soy sauce",
      "1 tsp gochujang (Korean chili paste)",
      "Sesame seeds for garnish",
    ],
    instructions: [
      "Heat vegetable oil in a large skillet or wok over medium-high heat.",
      "Add kimchi and stir-fry for 2 minutes.",
      "Add rice and break up any clumps.",
      "Mix in kimchi juice, soy sauce, and gochujang, stir-frying for 3-4 minutes.",
      "Push rice to one side and crack eggs into the empty space.",
      "Scramble eggs, then mix with the rice.",
      "Drizzle with sesame oil and garnish with green onions and sesame seeds.",
    ],
    tags: ["Quick", "One-Pot"],
    isSurprise: true,
    nutrition: [
      { name: "Calories", value: "350 kcal" },
      { name: "Protein", value: "12g" },
      { name: "Carbs", value: "48g" },
      { name: "Fat", value: "14g" },
    ],
  },

  // Original mock recipes
  {
    id: "1",
    title: "Tomato Basil Pasta",
    cuisine: "Italian",
    cookingTime: "25 mins",
    ingredients: [
      "8 oz pasta",
      "2 cups cherry tomatoes",
      "3 cloves garlic",
      "1/4 cup fresh basil",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
      "Parmesan cheese (optional)",
    ],
    instructions: [
      "Bring a large pot of salted water to a boil. Add pasta and cook according to package directions.",
      "While pasta cooks, heat olive oil in a large skillet over medium heat.",
      "Add minced garlic and cook until fragrant, about 30 seconds.",
      "Add halved cherry tomatoes and cook until they begin to burst, about 5-7 minutes.",
      "Drain pasta, reserving 1/4 cup of pasta water.",
      "Add pasta to the skillet with tomatoes, along with the reserved pasta water.",
      "Tear fresh basil leaves and add to the pasta. Season with salt and pepper.",
      "Serve hot with grated Parmesan cheese if desired.",
    ],
    tags: ["Vegetarian", "Quick", "Pasta"],
    nutrition: [
      { name: "Calories", value: "380 kcal" },
      { name: "Protein", value: "12g" },
      { name: "Carbs", value: "58g" },
      { name: "Fat", value: "12g" },
    ],
  },
  {
    id: "2",
    title: "Chickpea Curry",
    cuisine: "Indian",
    cookingTime: "30 mins",
    ingredients: [
      "2 cans chickpeas",
      "1 onion",
      "2 cloves garlic",
      "1 tbsp ginger",
      "1 can diced tomatoes",
      "2 tbsp curry powder",
      "1 can coconut milk",
      "Fresh cilantro",
      "Salt to taste",
    ],
    instructions: [
      "Dice onion, mince garlic, and grate ginger.",
      "Heat oil in a large pot over medium heat. Add onion and cook until translucent.",
      "Add garlic and ginger, cook for 1 minute until fragrant.",
      "Add curry powder and stir for 30 seconds.",
      "Add diced tomatoes and simmer for 5 minutes.",
      "Drain and rinse chickpeas, then add to the pot.",
      "Pour in coconut milk and simmer for 15 minutes.",
      "Season with salt to taste and garnish with fresh cilantro.",
    ],
    tags: ["Vegan", "Gluten-Free", "Spicy"],
    nutrition: [
      { name: "Calories", value: "420 kcal" },
      { name: "Protein", value: "15g" },
      { name: "Carbs", value: "52g" },
      { name: "Fat", value: "18g" },
    ],
  },
  {
    id: "3",
    title: "Kimchi Fried Rice",
    cuisine: "Korean",
    cookingTime: "20 mins",
    ingredients: [
      "2 cups cooked rice",
      "1 cup kimchi",
      "2 eggs",
      "2 green onions",
      "1 tbsp sesame oil",
      "1 tbsp soy sauce",
      "1 tsp gochujang (Korean chili paste)",
    ],
    instructions: [
      "Chop kimchi and green onions.",
      "Heat sesame oil in a large skillet or wok over medium-high heat.",
      "Add kimchi and stir-fry for 2 minutes.",
      "Add rice and break up any clumps.",
      "Mix in soy sauce and gochujang, stir-frying for 3-4 minutes.",
      "Push rice to one side and crack eggs into the empty space.",
      "Scramble eggs, then mix with the rice.",
      "Garnish with sliced green onions and serve hot.",
    ],
    tags: ["Spicy", "Quick", "One-Pot"],
    isSurprise: true,
    nutrition: [
      { name: "Calories", value: "350 kcal" },
      { name: "Protein", value: "12g" },
      { name: "Carbs", value: "48g" },
      { name: "Fat", value: "14g" },
    ],
  },
]
